---
- name: define and start beaker networks
  virt_net:
    command: define
    name: "{{ item.name }}"
    xml: "{{ lookup('template', 'config.xml.j2') }}"
  with_items: "{{ libvirt_bridges }}"

- name: activate beaker networks
  virt_net:
    state: active
    name: "{{ item.name }}"
  with_items: "{{ libvirt_bridges }}"

- name: gather network information
  virt_net:
    command: info
    name: "{{ item.name }}"
  with_items: "{{ libvirt_bridges }}"
  when: item.name.startswith('beaker')
  register: configured_networks

- name: add hostname mapping
  lineinfile: dest=/etc/hosts line="{{ item.item.hosts[0].ip }} {{ item.item.hosts[0].name }}"
  with_items: "{{ configured_networks.results }}"
