# This playbook adds a few task RPMs to beaker server
---
- hosts: localhost
  tasks:
    - name: create temporary directory
      shell: mktemp -d
      register: tempdir
    - name: download task rpms
      command: wget -r -np -nc -P "{{ tempdir.stdout }}" https://beaker-project.org/tasks/
    - name: find rpms
      shell: ls {{ tempdir.stdout }}/beaker-project.org/tasks/*.rpm
      register: rpms
    - name: add tasks to beaker server
      command: bkr task-add --hub="http://beaker-server-lc.beaker/bkr"
            --username={{ beaker_server_admin_user }} --password={{ beaker_server_admin_pass }} {{ item }}
      with_items: rpms.stdout_lines
      failed_when: no
      changed_when: no
      when: tempdir.rc == 0
    - name: remove temporary directory
      file: path={{ tempdir.stdout }} state=absent
