---
- import_playbook: setup_beaker.yml
- hosts: beaker-server-lc.beaker
  remote_user: root
  vars_files:
    - beaker_vars.yml
  roles:
    - { role: tests, tags: tests }

- hosts: localhost
  tasks:
    - name: clone beaker repository
      git:
        repo: git://git.beaker-project.org/beaker
        dest: /tmp/beaker
        track_submodules: yes
- import_playbook: setup_sandbox.yml
  vars:
    sandbox:
      git_repository: /tmp/beaker
