---
- name: be sure libselinux-python is installed
  yum: name=libselinux-python state=present

- include: yumrepos.yml

- name: disable selinux
  selinux: state=disabled

- name: disable firewall
  service: name=iptables state=stopped enabled=no

- name: install basic packages
  yum: name={{ item }} state=present
  with_items:
    - beaker-server
    - beaker-lab-controller
    - autofs
    - MySQL-python
    - tftp-server
    - mod_ssl
    - libvirt-client
    - wget

- include: database.yml

- name: start the Apache server and the Beaker daemon
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
    - beakerd
- include: labcontroller.yml
# set up test vms
- name: transfer the add_test_systems script
  copy: src=add_test_systems.sh dest=/usr/local/bin/add_test_systems.sh owner=root group=root mode=0755 backup=no

- name: run add_test_systems script
  command: sh /usr/local/bin/add_test_systems.sh {{ beaker_server_admin_user }} {{ beaker_server_admin_pass }}

- include: distros.yml
