---
# the rhel repos can be used on centos
- name: put beaker server repos on centos or rhel systems
  action: copy src="{{ item }}" dest="/etc/yum.repos.d/{{ item }}"
  with_items:
    - beaker-server-rhel.repo
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: put beaker server repos on Fedora systems
  action: copy src="{{ item }}" dest="/etc/yum.repos.d/{{ item }}"
  with_items:
    - beaker-server-fedora.repo
  when: ansible_distribution == 'Fedora'
