---
- name: create storage directory
  file:
    path: "{{ libvirt_storage_path }}"
    state: directory

- name: create volume config
  template:
    src: volume.xml.j2
    dest: "{{ libvirt_storage_path }}/{{ item.name }}.xml"
  with_items: libvirt_volumes
  register: configure_vol_result

- name: check volume states
  command: virsh vol-info {{ item.item.name }} default
  failed_when: no
  changed_when: no
  register: check_vol_states_result
  with_items: configure_vol_result.results

- name: delete existing volume
  command: virsh vol-delete {{ item[0].item.name }} default
  when: item[1].rc == 0 and item[0].changed
  with_together:
  - configure_vol_result.results
  - check_vol_states_result.results

- name: create volume
  command: virsh vol-create default --file /{{ libvirt_storage_path }}/{{ item.item.name }}.xml
  when: item.changed
  with_items: configure_vol_result.results
