# Based on https://github.com/henrysher/fedora-infra-ansible/blob/master/tasks/yumrepos.yml
---
# the rhel repos can be used on centos
- name: put beaker server repos on centos or rhel
  action: copy src="{{ item }}" dest="/etc/yum.repos.d/{{ item }}"
  with_items:
    - beaker-server-rhel.repo
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: put beaker server repos on centos or rhel
  action: copy src="{{ item }}" dest="/etc/yum.repos.d/{{ item }}"
  with_items:
    - beaker-server-fedora.repo
  when: ansible_distribution == 'Fedora'
